# Generated by Django 5.1.3 on 2024-11-30 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lift",
            old_name="repitions",
            new_name="repetitions",
        ),
        migrations.AlterField(
            model_name="lift",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
